export const educationMapping: Record<string, Record<string, string[]>> = {
  // Collège classes
  "7ème année de base": {
    _default: [
      "Arabe",
      "Français",
      "Anglais",
      "Mathématiques",
      "Sciences Physiques",
      "Sciences de la Vie et de la Terre",
      "Histoire-Géographie",
      "Éducation Civique",
      "Éducation Islamique",
      "Éducation Artistique",
      "Éducation Physique",
      "Technologie",
    ],
  },
  "8ème année de base": {
    _default: [
      "Arabe",
      "Français",
      "Anglais",
      "Mathématiques",
      "Sciences Physiques",
      "Sciences de la Vie et de la Terre",
      "Histoire-Géographie",
      "Éducation Civique",
      "Éducation Islamique",
      "Éducation Artistique",
      "Éducation Physique",
      "Technologie",
    ],
  },
  "9ème année de base": {
    _default: [
      "Arabe",
      "Français",
      "Anglais",
      "Mathématiques",
      "Sciences Physiques",
      "Sciences de la Vie et de la Terre",
      "Histoire-Géographie",
      "Éducation Civique",
      "Éducation Islamique",
      "Éducation Artistique",
      "Éducation Physique",
      "Technologie",
    ],
  },

  // Lycée classes
  "1ère année secondaire": {
    _default: [
      "Arabe",
      "Français",
      "Anglais",
      "Mathématiques",
      "Sciences Physiques",
      "Sciences de la Vie et de la Terre",
      "Histoire-Géographie",
      "Éducation Islamique",
      "Éducation Physique",
      "Technologie",
      "Informatique",
    ],
  },
  "2ème année secondaire": {
    Lettres: [
      "Arabe",
      "Français",
      "Anglais",
      "Philosophie",
      "Histoire-Géographie",
      "Éducation Islamique",
      "Éducation Physique",
    ],
    Sciences: [
      "Mathématiques",
      "Sciences Physiques",
      "Sciences de la Vie et de la Terre",
      "Informatique",
      "Français",
      "Anglais",
      "Arabe",
      "Éducation Islamique",
      "Éducation Physique",
    ],
    "Économie et Gestion": [
      "Économie",
      "Gestion",
      "Comptabilité",
      "Mathématiques",
      "Français",
      "Anglais",
      "Arabe",
      "Éducation Islamique",
      "Éducation Physique",
    ],
    Techniques: [
      "Technologie",
      "Mathématiques",
      "Sciences Physiques",
      "Français",
      "Anglais",
      "Arabe",
      "Éducation Islamique",
      "Éducation Physique",
    ],
  },
  "3ème année secondaire": {
    Lettres: [
      "Arabe",
      "Français",
      "Anglais",
      "Philosophie",
      "Histoire-Géographie",
      "Éducation Islamique",
      "Éducation Physique",
    ],
    "Sciences Expérimentales": [
      "Sciences de la Vie et de la Terre",
      "Mathématiques",
      "Sciences Physiques",
      "Français",
      "Anglais",
      "Arabe",
      "Éducation Islamique",
      "Éducation Physique",
    ],
    Mathématiques: [
      "Mathématiques",
      "Sciences Physiques",
      "Informatique",
      "Français",
      "Anglais",
      "Arabe",
      "Éducation Islamique",
      "Éducation Physique",
    ],
    Techniques: [
      "Technologie",
      "Mathématiques",
      "Sciences Physiques",
      "Français",
      "Anglais",
      "Arabe",
      "Éducation Islamique",
      "Éducation Physique",
    ],
    "Économie et Gestion": [
      "Économie",
      "Gestion",
      "Comptabilité",
      "Mathématiques",
      "Français",
      "Anglais",
      "Arabe",
      "Éducation Islamique",
      "Éducation Physique",
    ],
  },
  "4ème année secondaire (BAC)": {
    Lettres: [
      "Arabe",
      "Français",
      "Anglais",
      "Philosophie",
      "Histoire-Géographie",
      "Éducation Islamique",
      "Éducation Physique",
    ],
    "Sciences Expérimentales": [
      "Sciences de la Vie et de la Terre",
      "Mathématiques",
      "Sciences Physiques",
      "Français",
      "Anglais",
      "Arabe",
      "Éducation Islamique",
      "Éducation Physique",
    ],
    Mathématiques: [
      "Mathématiques",
      "Sciences Physiques",
      "Informatique",
      "Français",
      "Anglais",
      "Arabe",
      "Éducation Islamique",
      "Éducation Physique",
    ],
    "Sciences techniques": [
      "Technologie",
      "Mathématiques",
      "Sciences Physiques",
      "Français",
      "Anglais",
      "Arabe",
      "Éducation Islamique",
      "Éducation Physique",
    ],
    "Économie et Gestion": [
      "Économie",
      "Gestion",
      "Comptabilité",
      "Mathématiques",
      "Français",
      "Anglais",
      "Arabe",
      "Éducation Islamique",
      "Éducation Physique",
    ],
  },
};
