export const professorSpecialties: Record<string, string[]> = {
  Collège: [
    "Professeur d'Arabe",
    "Professeur de Français",
    "Professeur d'Anglais",
    "Professeur de Mathématiques",
    "Professeur de Sciences Physiques",
    "Professeur de Sciences de la Vie et de la Terre",
    "Professeur d'Histoire-Géographie",
    "Professeur d'Éducation Civique",
    "Professeur d'Éducation Islamique",
    "Professeur d'Éducation Artistique",
    "Professeur d'Éducation Physique",
    "Professeur de Technologie",
  ],
  Lycée: [
    "Professeur d'Arabe",
    "Professeur de Français",
    "Professeur d'Anglais",
    "Professeur d'Espagnol",
    "Professeur d'Allemand",
    "Professeur d'Italien",
    "Professeur de Chinois",
    "Professeur de Russe",
    "Professeur de Turc",
    "Professeur de Japonais",
    "Professeur de Mathématiques",
    "Professeur de Sciences Physiques",
    "Professeur de Sciences de la Vie et de la Terre",
    "Professeur d'Informatique",
    "Professeur de Technologie",
    "Professeur de Philosophie",
    "Professeur d'Économie",
    "Professeur de Gestion",
    "Professeur de Comptabilité",
    "Professeur d'Histoire-Géographie",
    "Professeur d'Éducation Civique",
    "Professeur d'Éducation Islamique",
    "Professeur d'Éducation Artistique",
    "Professeur d'Éducation Physique",
  ],
};
