export const professorSpecialties: Record<string, string[]> = {
  Collège: [
    "Professeur d'Arabe",
    "Professeur de Français",
    "Professeur d'Anglais",
    "Professeur de Mathématiques",
    "Professeur de Sciences Physiques",
    "Professeur de Sciences de la Vie et de la Terre",
    "Professeur d'Histoire-Géographie",
    "Professeur d'Éducation Civique",
    "Professeur d'Éducation Islamique",
    "Professeur d'Éducation Artistique",
    "Professeur d'Éducation Physique",
    "Professeur de Technologie",
  ],
  Lycée: [
    "Professeur d'Arabe",
    "Professeur de Français",
    "Professeur d'Anglais",
    "Professeur d'Espagnol",
    "Professeur d'Allemand",
    "Professeur d'Italien",
    "Professeur de Chinois",
    "Professeur de Russe",
    "Professeur de Turc",
    "Professeur de Japonais",
    "Professeur de Mathématiques",
    "Professeur de Sciences Physiques",
    "Professeur de Sciences de la Vie et de la Terre",
    "Professeur d'Informatique",
    "Professeur de Technologie",
    "Professeur de Philosophie",
    "Professeur d'Économie",
    "Professeur de Gestion",
    "Professeur de Comptabilité",
    "Professeur d'Histoire-Géographie",
    "Professeur d'Éducation Civique",
    "Professeur d'Éducation Islamique",
    "Professeur d'Éducation Artistique",
    "Professeur d'Éducation Physique",
  ],
};

export const subjectToSpecialty: Record<string, string> = {
  Arabe: "Professeur d'Arabe",
  Français: "Professeur de Français",
  Anglais: "Professeur d'Anglais",
  Espagnol: "Professeur d'Espagnol",
  Allemand: "Professeur d'Allemand",
  Italien: "Professeur d'Italien",
  Chinois: "Professeur de Chinois",
  Russe: "Professeur de Russe",
  Turc: "Professeur de Turc",
  Japonais: "Professeur de Japonais",
  Mathématiques: "Professeur de Mathématiques",
  "Sciences Physiques": "Professeur de Sciences Physiques",
  "Sciences de la Vie et de la Terre":
    "Professeur de Sciences de la Vie et de la Terre",
  "Histoire-Géographie": "Professeur d'Histoire-Géographie",
  Philosophie: "Professeur de Philosophie",
  Économie: "Professeur d'Économie",
  Gestion: "Professeur de Gestion",
  Comptabilité: "Professeur de Comptabilité",
  Technologie: "Professeur de Technologie",
  Informatique: "Professeur d'Informatique",
  "Éducation Civique": "Professeur d'Éducation Civique",
  "Éducation Islamique": "Professeur d'Éducation Islamique",
  "Éducation Artistique": "Professeur d'Éducation Artistique",
  "Éducation Physique": "Professeur d'Éducation Physique",
};

export const specialtyToSubject: Record<string, string> = Object.fromEntries(
  Object.entries(subjectToSpecialty).map(([key, value]) => [value, key])
);

export const specialties = Object.values(subjectToSpecialty);
